name: CI
on: { push: { branches: [master] }, pull_request: null, workflow_call: null }
permissions: { contents: read }
jobs:
  node:
    runs-on: ubuntu-latest
    env: { RUNNER_PM: bun }
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/ready
      - run: bun install --ignore-scripts
      - run: run -s generate bundle
      - run: run -p typecheck verify test lint
      - run: run package.json:version
  deno:
    runs-on: ubuntu-latest
    env: { RUNNER_PM: deno }
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/ready
      - run: runner install -f deno:ci
