name: Publish to NPM
on: { workflow_call: null }
jobs:
  publish:
    name: Publish recipe-tmlanguage
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    environment: { name: npm, url: "${{ steps.meta.outputs.url }}" }
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with: { node-version: latest, registry-url: https://registry.npmjs.org }
      - uses: ./.github/actions/ready
      - run: runner install --pm=bun generate bundle
      - id: meta
        run: echo "url=https://npm.im/package/$(yq -r .name package.json)/v/$(yq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - run: bunx npm@latest publish --provenance --access public --ignore-scripts
